### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by twhitacre** [tiy-atl-js-sept-2015/Assignments#123]
@jefdonmar this is your issue for *Assignment 5*. Please comment below with the required deliverable(s) and close this issue when you are finished.

**Comment by jefdonmar** [comment]
Jus had some spacing errors that I think could have been fixed in the code 

https://github.com/jefdonmar/JS-Intro

Here is a link to my blog post 

http://jefdonmar.tumblr.com/post/130073785431/1st-week-of-coding-school

**Comment by jisaacks** [comment]
Great job, in some of your answers you put `undefined` when in fact there was a value. It looks like you tested this on the console, you'll remember I explained that on the console a statement always returns undefined, but the value assigned to variable still exists.
